### ISSUE TITLE
Operator overloading for complex numbers

### ISSUE THREAD

**Issue by RSBat** [mipt-npm/kmath#500]
It would be nice to have [operator overloads](https://kotlinlang.org/docs/operator-overloading.html) for complex numbers to write expressions in a more straightforward way like this
```
val a = Complex(1, 0)
val b = Complex(0, 1)
val c = a + b
```
instead of
```
val c = add(a, b)
```

**Comment by altavir** [comment]
The KMath ideology is to use `Algebra` contexts for operations instead of binding operations to types. There are several reasons for that:
* There could be different definitions of operations for the same type (for example you can concatenate lists or do value-by-value addition).
* We need to propagate operations. For example we want to be able to add to generic vectors. For this we need to abstract away the addition.
* Sometimes we need to replace one type of objects with another one and we would like to do it without relying on implementation of operations.

So in order to do what you want in KMath you just need to run operations in the relevant scope like it is done [here](https://github.com/mipt-npm/kmath/blob/a8182fad23417f4302ea77ccdeba3b931e50a471/examples/src/main/kotlin/space/kscience/kmath/operations/complexDemo.kt#L15-L40). 

Also, if for your application, you are sure that you do not need the flexibility, you always can add a number of top level extensions like it is done [here](https://github.com/mipt-npm/kmath/blob/dev/kmath-for-real/src/commonMain/kotlin/space/kscience/kmath/real/DoubleVector.kt). In future, if the proposal of [file-level receivers](https://github.com/Kotlin/KEEP/issues/209) is accepted, one would be also able to add the algebra scope for the whole file.

**Comment by RSBat** [comment]
Makes sense. I went with top level extensions in my project since I just needed complex math and didn't want to implement it myself.
